using ModelContextProtocol.Server;
using ReviewCheck.Llm;
using ReviewCheck.Mcp.Provider;

namespace ReviewCheck.Mcp;

/// <summary>How a block's explanation is produced for a given review.</summary>
public enum NarrationMode
{
    /// <summary>The user's own Anthropic key (BYO) — grounded.</summary>
    KeyLlm,
    /// <summary>The host model via MCP sampling — grounded, no key.</summary>
    HostSampling,
    /// <summary>Deterministic structural narrative — no LLM.</summary>
    Facts,
}

/// <summary>
/// Chooses the narrator PER REVIEW and returns a user-facing notice. The choice can only be made
/// at request time because the host's <c>sampling</c> capability is known only after the MCP
/// handshake — so <c>get_review_plan</c> resolves it, not startup DI. Decision tree:
/// <list type="number">
///   <item>a configured key → <see cref="NarrationMode.KeyLlm"/> (no notice);</item>
///   <item>no key + host supports sampling → <see cref="NarrationMode.HostSampling"/> (hosting notice);</item>
///   <item>otherwise → <see cref="NarrationMode.Facts"/> (a deliberate-choice notice).</item>
/// </list>
/// <c>REVIEWCHECK_NARRATOR=facts</c> forces facts (a deliberate opt-in, so no notice).
/// </summary>
public sealed class NarratorResolver(HttpClient http, bool factsForced)
{
    /// <summary>Default used when no resolver is injected (tests, stub mode): always facts.</summary>
    public static NarratorResolver FactsOnly { get; } = new(new HttpClient(), factsForced: true);

    public const string HostingNotice =
        "Hosting mode: these explanations are generated by your host model (no dedicated API key) " +
        "and are still checked against ReviewCheck's grounding rules.";

    // Framed as a deliberate choice, not a defect (the user's guidance): a generic grounded
    // description that asks you to understand the code is safer than a confident wrong guess.
    public const string FactsNotice =
        "No API key and your host does not support hosting mode, so these explanations are the " +
        "deterministic structural narrative. This is deliberate: a generic description that asks " +
        "you to work out what the code does yourself is safer than confident but wrong suggestions. " +
        "Set REVIEWCHECK_ANTHROPIC_KEY (or use a host that supports sampling) for richer, grounded explanations.";

    /// <summary>Pure decision (testable without an MCP server).</summary>
    public static (NarrationMode Mode, string? Notice) Decide(bool keyConfigured, bool factsForced, bool samplingSupported)
    {
        if (factsForced) return (NarrationMode.Facts, null);
        if (keyConfigured) return (NarrationMode.KeyLlm, null);
        if (samplingSupported) return (NarrationMode.HostSampling, HostingNotice);
        return (NarrationMode.Facts, FactsNotice);
    }

    // MCP9005: the MCP `sampling` capability is deprecated in the spec (2026-07-28, SEP-2577) but
    // still present and functional in this SDK. Hosting mode relies on it deliberately; if a future
    // SDK removes it, the decision tree degrades to facts (with its notice) automatically.
#pragma warning disable MCP9005
    public (IBlockNarrator Narrator, string? Notice) Resolve(McpServer? server)
    {
        var samplingSupported = server?.ClientCapabilities?.Sampling is not null;
        var (mode, notice) = Decide(AnthropicByoProvider.IsConfigured, factsForced, samplingSupported);

        IBlockNarrator narrator = mode switch
        {
            NarrationMode.KeyLlm => new LlmAdapter(new AnthropicByoProvider(http)),
            NarrationMode.HostSampling => new LlmAdapter(new HostSamplingLlmProvider(server!.AsSamplingChatClient())),
            _ => new FactsNarrator(),
        };
        return (narrator, notice);
    }
#pragma warning restore MCP9005
}
